### PR TITLE
Header component

### PR DESCRIPTION
**Pull request by arestus**
In this pull-request I mainly styled three header sizes from the mockup. Changed styles naming from BEM to camelCase. Added logo images and logic for their rendering. Also resolved the conflicts that were before the push after git pull. Everything should work. If I'm not mistaken, Alex sent you a branch with a container component.

### CODE REVIEW

**Review by Larisa-Antsifrova — CHANGES_REQUESTED** [review]
Yarik, it looks great! Especially responsiveness and the LogOut button :))
I leave the PR unmerged though to fix Logo into Link to lead to /dashboard/home as we discussed.

**Review by Larisa-Antsifrova — APPROVED** [review]
Looks nice :)

**Comment by arestus** [comment]
And after the merge, can I write something here? Maybe yes

**Comment by Larisa-Antsifrova** [comment]
Yes, but I will pokusaiu tebia.

**Pull request merged**
